services:
  spark:
    image: jupyter/pyspark-notebook:spark-3.5.0
    container_name: spark
    ports:
      - "8889:8888"
      - "4040-4045:4040-4045"
    volumes:
      - ./src:/home/jovyan/work/src
    depends_on:
      - kafka
      - pg